# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865e7ea76f78d27fe9e7565e3005040c8fdb5921d8dc58e2c31b1977304f5a471777b38afbb49370ab75561d1be928610c4d9b49e467a6cd9f2a9c87fe3a97af

test:
  secret_key_base: 0bdade34eb63cad33a339e5bd6cb35f3d3bb8c02209af199b298e22528ddd4fd3ed7f14aa8158f62769f660b5ab022e60459e6a1513afe04c27afdcc3577b79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
