# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358086bec08d66f4082fbeb1bb2efa0ae3a3d35bdaf3a95f1f2bf907aa2dd8a8d2e4394a90f1d54a0a21cb966cce010aae3ffcb2639d684fa83ca3b09e275a1f

test:
  secret_key_base: f508a99161218b1393759274863e9e835e6441cf22d6d28bc230e854773cf00dc6de5cca9f7c608a1cda6f16ed1ca9b1d0b138de2004ff8b1e86b5b709f79377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
